# Generated by Django 5.2 on 2025-05-05 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoarticulo',
            name='grupo_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineaarticulo',
            name='linea_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupoarticulo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lineaarticulo')),
            ],
            options={
                'db_table': 'articulos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('lista_precio_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
            ],
            options={
                'db_table': 'lista_precios',
            },
        ),
    ]
